name: "Code check"

on:
  push:
    branches:
      - "main"

  workflow_call:

  pull_request:
    paths:
      - "src/**"
      - "tests/**"
      - "composer.json"
      - "ecs.php"
      - "extension-ecs.php"
      - "rector.php"
      - "extension-rector.php"
      - "phpstan.neon"
      - "phpstan-baseline.neon"
      - "phpunit.xml"

concurrency:
  group: conventions-check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code:
    name: "Code check"
    strategy:
      matrix:
        phpVersion: [ "8.3", "8.4", "8.5" ]
    uses: wrk-flow/reusable-workflows/.github/workflows/php-check.yml@a175c9b9239a356b40362a649c790ced8efc9e42
    with:
      phpVersion: "${{ matrix.phpVersion }}"

  tests:
    name: "Run tests"
    strategy:
      matrix:
        phpVersion: [ "8.3", "8.4", "8.5" ]
    uses: wrk-flow/reusable-workflows/.github/workflows/php-tests.yml@a175c9b9239a356b40362a649c790ced8efc9e42
    with:
      gistOnPhpVersion: "8.3"
      gistID: 0b0340bf7e806524a632347d0b9219ea
      phpVersion: "${{ matrix.phpVersion }}"
    secrets:
      GIST_SECRET: ${{ secrets.GIST_SECRET }}

