name: "Code check"

on:
  push:
    branches:
      - "main"

  workflow_call:

  pull_request:
    paths:
      - "src/**"
      - "tests/**"
      - "composer.json"
      - "ecs.php"
      - "extension-ecs.php"
      - "rector.php"
      - "extension-rector.php"
      - "phpstan.neon"
      - "phpstan-baseline.neon"
      - "phpunit.xml"

concurrency:
  group: conventions-check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code:
    name: "Code check"
    strategy:
      matrix:
        phpVersion: [ "8.3", "8.4", "8.5" ]
    uses: wrk-flow/reusable-workflows/.github/workflows/php-check.yml@40a47d615aafd60bc83322be7d18b53aade5c55f
    with:
      phpVersion: "${{ matrix.phpVersion }}"
    secrets: inherit

  tests:
    name: "Run tests"
    strategy:
      matrix:
        phpVersion: [ "8.3", "8.4", "8.5" ]
    uses: wrk-flow/reusable-workflows/.github/workflows/php-tests.yml@40a47d615aafd60bc83322be7d18b53aade5c55f
    with:
      gistOnPhpVersion: "8.3"
      gistID: 0b0340bf7e806524a632347d0b9219ea
      phpVersion: "${{ matrix.phpVersion }}"
    secrets: inherit

